// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGgzz86vlzRkM5rcG6wT88OSidCtJCwWY',
    appId: '1:585374901800:web:76ed28aef2c75f339b771d',
    messagingSenderId: '585374901800',
    projectId: 'fir-d-app-c3e91',
    authDomain: 'fir-d-app-c3e91.firebaseapp.com',
    storageBucket: 'fir-d-app-c3e91.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAeTCN1uaVuZ9kjGHXeua_BnPLkEw4sIXo',
    appId: '1:585374901800:android:977fc213d3470f139b771d',
    messagingSenderId: '585374901800',
    projectId: 'fir-d-app-c3e91',
    storageBucket: 'fir-d-app-c3e91.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEj6gn5Nfq9eTrc_-JRLGrtmCH1loDwmo',
    appId: '1:585374901800:ios:dfcd226d1dc5c1e79b771d',
    messagingSenderId: '585374901800',
    projectId: 'fir-d-app-c3e91',
    storageBucket: 'fir-d-app-c3e91.appspot.com',
    iosBundleId: 'com.naumanbutt2002.firebasedApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEj6gn5Nfq9eTrc_-JRLGrtmCH1loDwmo',
    appId: '1:585374901800:ios:dfcd226d1dc5c1e79b771d',
    messagingSenderId: '585374901800',
    projectId: 'fir-d-app-c3e91',
    storageBucket: 'fir-d-app-c3e91.appspot.com',
    iosBundleId: 'com.naumanbutt2002.firebasedApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBGgzz86vlzRkM5rcG6wT88OSidCtJCwWY',
    appId: '1:585374901800:web:d01223f39024f6ea9b771d',
    messagingSenderId: '585374901800',
    projectId: 'fir-d-app-c3e91',
    authDomain: 'fir-d-app-c3e91.firebaseapp.com',
    storageBucket: 'fir-d-app-c3e91.appspot.com',
  );
}
